meta-rz-common/recipes-debian: Fix error when libunistring rebuild
libunistring can be built normally if build from scratch.
However, if the build is rerun, by user force command or by chaning
build target, a compile error will occur
Example:
	$ MACHINE=ek874 bitbake libunistring
	$ MACHINE=hihope-rzg2n bitbake libunistring
or	$ MACHINE=ek874 bitbake libunistring -C compile
	ERROR: libunistring-0.9.10-r0 do_compile: oe_runmake failed
	...
	/bin/bash: gperf: command not found

For an unknown reason, after built sucessfully in 1st time, when rerun
do_compile run differently with 1st time, and requires gperf.
(1st build doesn't require gperf)
The reason of this difference is not clear, but it only happens
after do_package.
Without do_package, this issue does not happen
	$ MACHINE=ek874 bitbake libunistring -c install
	$ MACHINE=ek874 bitbake libunistring -fc compile
	#(no issue)
	$ MACHINE=ek874 bitbake libunistring -C compile
	#(no issue)
	$ MACHINE=ek874 bitbake libunistring -fc compile
	ERROR: libunistring-0.9.10-r0 do_compile: oe_runmake failed
	#(error happens because do_package was run in above command)

Add DEPENDS to gperf-native as a workaround to prevent error.
But this does not solve the reason why the rerun of do_compile
different with previous run.

Signed-off-by: Hung Tran <hung.tran.jy@renesas.com>