virtualization-layer: docker-ce: Fix issue about Postinstall scriptlets of ['docker-ce'] have failed
There is an error Postinstall scriptlets of ['docker-ce'] have failed
when building with docker:
ERROR: core-image-weston-1.0-r0 do_rootfs: Postinstall scriptlets of ['docker-ce'] have failed. If the intention is to defer them to first boo
t,
then please place them into pkg_postinst_ontarget_${PN} ().
Deferring to first boot via 'exit 1' is no longer supported.

Refer solution from
"https://github.com/Xilinx/meta-virtualization/issues/4#issuecomment-590532621"

Signed-off-by: hienhuynh <hien.huynh.px@renesas.com>