kernel-module-gles: fix compile issue when switch to kernel-rt
'struct mutex' was changed in kernel-rt, below issue occur when compiling:
   error: 'struct mutex' has no member named 'count'
This commit temporary remove the error code, futher invesitation are needed.

Signed-off-by: vietn <vietn@fsoft.com.vn>
Signed-off-by: Binh Nguyen <binh.nguyen.uw@renesas.com>