meta-rz-common/recipes-debian: Fix build error on Debian packages when change target
When user build a target (Ex: hihope-rzg2m), then change to another compatible
target (Ex: hihope-rzg2n), Yocto will rerun some tasks in previous build.
In normal package, task from do_patch will rerun. When rerun do_patch knows
that all patches were already applied, thus not apply them again.

But packages in recipe-debian have 2 additional tasks: do_debian_unpackage_extra
and do_debian_patch. In some ackages, these tasks meet below errors when rerun:
	ERROR: glibc-2.28-r0 do_debian_patch: unknown quilt patches already applied
	ERROR: pkgconfig-0.29-r0 do_debian_unpack_extra: Execution of 'run.do_debian_unpack_extra.1199967' failed with exit code 1

The first error with do_debian_patch happens because recipes-debian has a
workaround to avoid conflict of do_debian_patch with Yocto normal do_patch
(use same .pc directory for quilt).
This workaround cannot work if do_debian_patch runs 2nd time on a source dir,
so current implement just reports error and stops working.
	# confirm that other patches didn't applied
	if [ -d ${DEBIAN_QUILT_DIR} -o -d ${DEBIAN_QUILT_DIR_ESC} ]; then
		bbfatal "unknown quilt patches already applied"		# Error here
	fi

This commit solves the conflict of do_debian_patch and do_patch by using
different .pc dir for do_debian_patch.

The second error with do_debian_unpack_extra happens in a few packages.
In those packages, Debian patches set contains only 1 simple diff file, and
do_debian_unpack_extra applies that diff without waiting to de_debian_patch.
Because do_debian_unpack_extra use simple patch command to apply patch,
it will fail if rerun.
Fix it by removing the Debian diff file after applied. With this change
do_debian_unpack_extra will do nothing when rerun.

Signed-off-by: Hung Tran <hung.tran.jy@renesas.com>