cip-core-buster: Fix GDB compile error when building SDK
TRAP_HWBKPT is defined before including gdb_wait.h and causes below
error when building SDK with core-image-weston-sdk:

  | ../../gdb-8.0/gdb/nat/linux-ptrace.h:175:22: error: expected identifier before numeric constant
  |  # define TRAP_HWBKPT 4
  |                       ^
Including gdb_wait.h earlier can fix it.

Signed-off-by: Quynh Nguyen <quynh.nguyen.xb@renesas.com>