SDK: Fix error when compiling ppp tool for SDK
When building SDK, below error will happen.
It happens because of a problem in header file
if_pppox.h of current kernel.

  error: field ‘addr’ has incomplete type
  struct sockaddr_in addr; /* IP address and port to send to */

Reference: https://patchwork.kernel.org/patch/7401861/

Signed-off-by: Hung Tran <hung.tran.jy@renesas.com>