templates: fix error with nativesdk-glibc-locale
Setting GLIBCVERSION does not cover nativesdk-glibc-localte.
Thus, poky version is used instead of the version we set.
This causes an error when start building:

ERROR: Task do_install in virtual:nativesdk:/home/rvc/yocto2.4_local/build/../meta-linaro/meta-linaro-toolchain/recipes-core/glibc/glibc-locale_linaro-2.20.bb depends upon non-existent task do_stash_locale in virtual:nativesdk:/home/rvc/yocto2.4_local/build/../meta-renesas/meta-rzg1/recipes-cip-core/glibc/glibc_debian.bb
ERROR: Command execution failed: 1

Signed-off-by: Hung Tran <hung.tran.jy@renesas.com>