bash: package bashbug separately
This commit is backported from commit id:
<852e8048d186b4d93110a4e2e1b10bde769f0d4d>
in poky for bash v4 and above.

It's a machine-specific script, which is causing conflicts
when multiple versions of bash are installed in multilib setting,
and it also does not really make sense for embedded systems anyway.

(From OE-Core rev: dbe57bd0aec855c81b03850367b3b483f622c328)

Below issue will be happened without applying this commit:
Error: Transaction check error:
  file /usr/bin/bashbug from install of lib32-bash-3.2.57-r0.armv7vet2hf_neon_vfpv4 conflicts with file from package bash-3.2.57-r0.aarch64

Signed-off-by: Alexander Kanavin <alexander.kanavin@linux.intel.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>
Signed-off-by: Hien Huynh <hien.huynh.px@renesas.com>